version: "3.5"
services:
  openldap:
    image: hatlonely/openldap:1.0.0
    hostname: openldap
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "${HOME}/var/docker/openldap/conf:/etc/ldap"
      - "${HOME}/var/docker/openldap/data:/var/lib/ldap"
    networks:
      - openldapnet
    environment:
      LDAP_ORGANISATION: "hatlonely"
      LDAP_DOMAIN: "hatlonely.com"
      LDAP_ADMIN_PASSWORD: "keaiduo1"
networks:
  openldapnet:
    name: openldapnet
