#!/usr/bin/env python3

import argparse
import sys

opmap = {
    'bin': '{:b}',
    'oct': '{:o}',
    'dec': '{:d}',
    'hex': '{:x}',
}

carrymap = {
    'bin': 2,
    'oct': 8,
    'dec': 10,
    'hex': 16,
}

parser = argparse.ArgumentParser(description='format integer')
parser.add_argument('input_format', type=str, nargs='?', default='dec',
                    choices=[*opmap], help='input format')
parser.add_argument('output_format', type=str, nargs='?', default='hex',
                    choices=[*carrymap], help='output format')
parser.add_argument('message', type=str, nargs='?', help='message')
args = parser.parse_args()

ofop = opmap[args.output_format]
ifcarry = carrymap[args.input_format]
if args.message:
    print(ofop.format(int(args.message, ifcarry)))
else:
    for line in sys.stdin:
        print(ofop.format(int(line[:-1], ifcarry)))
