#!/usr/bin/env python3
# python3 -m pip install murmurhash3

import mmh3
import hashlib
import argparse
import sys


def md5sum(message):
    m = hashlib.md5()
    m.update(message.encode())
    return m.hexdigest()


def murmur3(message):
    return (mmh3.hash64(message)[0]) % 2 ** 64


def murmur3_128(message):
    return mmh3.hash128(message)


parser = argparse.ArgumentParser(description='hash parser')
parser.add_argument('message', type=str, nargs='?', help='hash message')
parser.add_argument('-t', '--type', default='murmur3',
                    choices=['murmur3', 'murmur3_128', 'md5sum'], help='hash type')
args = parser.parse_args()

if args.message:
    print(getattr(sys.modules[__name__], args.type)(args.message))
else:
    for line in sys.stdin:
        print(getattr(sys.modules[__name__], args.type)(line[:-1]))
