#!/usr/bin/env bash

function install_redis() {
    mkdir -p source && cd source &&
    wget http://download.redis.io/releases/redis-4.0.9.tar.gz &&
    tar -xzvf redis-4.0.9.tar.gz &&
    cd redis-4.0.9 &&
    make -j8 &&
    PREFIX=$1 make install &&
    cp src/redis-trib.rb $1/bin
}

function install_lrzsz() {
    mkdir -p source && cd source &&
    wget https://ohse.de/uwe/releases/lrzsz-0.12.20.tar.gz &&
    tar -xzvf lrzsz-0.12.20.tar.gz &&
    cd lrzsz-0.12.20 &&
    ./configure &&
    make -j8 && PREFIX=$1 make install
}

function install_cmake() {
    mkdir -p source && cd source &&
    wget https://cmake.org/files/v3.12/cmake-3.12.0-rc3.tar.gz &&
    tar -xzvf cmake-3.12.0-rc3.tar.gz &&
    cd cmake-3.12.0-rc3 &&
    ./configure &&
    make -j8 && PREFIX=$1 make install
}

function install_python3() {
    if [[ $(uname -s) == "Darwin" ]]; then
        export CFLAGS="-I/usr/local/opt/openssl/include"
        export LDFLAGS="-L/usr/local/opt/openssl/lib"
    fi
    mkdir -p source && cd source &&
    wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz &&
    tar -zxvf Python-3.6.5.tgz &&
    cd Python-3.6.5 &&
    ./configure --enable-shared --prefix=$1 &&
    make -j8 &&
    make install &&
    $1/bin/python3 -m pip install pymysql &&
    $1/bin/python3 -m pip install murmurhash3 &&
    $1/bin/python3 -m pip install httplib2 &&
    $1/bin/python3 -m pip install kafka &&
    $1/bin/python3 -m pip install kafka-python &&
    $1/bin/python3 -m pip install pymongo &&
    $1/bin/python3 -m pip install psycopg2 &&
    $1/bin/python3 -m pip install pyquery &&
    $1/bin/python3 -m pip install elasticsearch &&
    $1/bin/python3 -m pip install rfc3339 &&
    $1/bin/python3 -m pip install markdown2 &&
    $1/bin/python3 -m pip install pymongo
}

function install_nodejs() {
    mkdir -p source && cd source &&
    wget https://npm.taobao.org/mirrors/node/v10.2.0/node-v10.2.0.tar.gz &&
    tar -xzvf node-v10.2.0.tar.gz &&
    cd node-v10.2.0 &&
    ./configure --prefix=$1 &&
    make -j8 &&
    make install
}

function install_aerospike() {
    mkdir -p source && cd source &&
    wget -O aerospike.tgz 'https://www.aerospike.com/download/server/latest/artifact/el6' &&
    tar -xvf aerospike.tgz &&
    cd aerospike-server-community-*-el6 &&
    sudo ./asinstall
}

function usage() {
    echo "usage: install <module> [prefix=./local]"
    echo "module list"
    echo "  redis"
    echo "  lrzsz"
    echo "  python3"
    echo "  nodejs"
    echo "  cmake"
    echo "  aerospike"
    echo "  glide"
    echo "  gologrus"
    echo "  goviper"
    echo "  goaws"
    echo "  goredis"
    echo "  gomurmur3"
}

output=$(pwd)/local
if [[ ! -z $2 ]]; then
    output=$2
fi
mkdir -p ${output}

case $1 in
    "redis") install_redis ${output};;
    "lrzsz") install_lrzsz ${output};;
    "python3") install_python3 ${output};;
    "nodejs") install_nodejs ${output};;
    "cmake") install_cmake ${output};;
    "aerospike") install_aerospike;;
    "glide") curl https://glide.sh/get | sh;;
    "gologrus") glide get github.com/sirupsen/logrus;;
    "goviper") glide get github.com/spf13/viper;;
    "goaws") glide get github.com/aws/aws-sdk-go;;
    "goredis") glide get github.com/go-redis/redis;;
    "gomurmur3") glide get github.com/spaolacci/murmur3;;
    *) usage;;
esac
