#!/usr/bin/env python3
# python3 -m pip install pymongo

from bson.objectid import ObjectId
import argparse
import sys

parser = argparse.ArgumentParser(description='get timestamp form mongoid')
parser.add_argument('message', type=str, nargs='?', help='message')
args = parser.parse_args()

if args.message:
    print(int(ObjectId(args.message).generation_time.timestamp()))
else:
    for line in sys.stdin:
        try:
            print(int(ObjectId(line[:-1]).generation_time.timestamp()))
        except Exception as e:
            print(e)
