#!/usr/bin/env python3

import argparse

resource = {
    "golang": [
        "github.com/spf13/viper",
        "github.com/spf13/pflag",
        "github.com/sirupsen/logrus",
        "github.com/sohlich/elogrus",
        "gopkg.in/olivere/elastic.v5",
        "github.com/jinzhu/gorm",
        "github.com/aws/aws-sdk-go",
        "github.com/smartystreets/goconvey",
        "github.com/spaolacci/murmur3",
        "github.com/emirpasic/gods",
        "github.com/satori/go.uuid",
        "github.com/mailru/easyjson",
        "github.com/json-iterator/go",
        "github.com/hashicorp/consul",
        "github.com/gogo/protobuf"
    ],
    "python": [
        "requests"
    ],
}


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""Example:
    python3 resource <key>
""",
    )
    parser.add_argument("key", nargs="?", type=str,
                        choices={*resource.keys()},
                        help="resource key")
    args = parser.parse_args()
    print("\n".join(resource[args.key]))


if __name__ == '__main__':
    main()
