#!/usr/bin/env python3

import argparse
import re
import os

html = """
<html>
<head>
    <script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
    <script src="https://cdn.bootcss.com/highlight.js/9.9.0/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.1.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- simplex/lumen/paper/flatly/darkly/yeti/readable/superhero/spacelab/cosmo/cerulean/cyborg/united -->
    <link href="https://cdn.bootcss.com/bootswatch/3.3.7/{style}/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/highlight.js/9.11.0/styles/github-gist.min.css" rel="stylesheet">
    <script>
        $(document).ready(function() {{
            hljs.initHighlightingOnLoad();

            var renderer = new marked.Renderer();

            renderer.html = function (html) {{
                console.log(html)
                return '';
            }}

            marked.setOptions({{
                renderer: renderer,
                gfm: true,
                tables: true,
                breaks: true,
                pedantic: true,
                sanitize: true,
                smartLists: true,
                smartypants: true
            }});

            marked.setOptions({{
                highlight: function(code) {{
                    return hljs.highlightAuto(code).value;
                }}
            }});

            $('#markdown').html(marked({markdown}));
            $('table').addClass('table table-striped table-hover');
            $('img').width('100%');
        }});
    </script>
    <title> {title} </title>
</head>
<body>

    <div class="row">
        <div class="col-md-6 col-md-offset-3" id="markdown">
        </div>
    </div>

</body>
</html>
"""


def format_line(line):
    line = re.sub(r'!\[(.*?)\]\((.*?)\)', r'![\1]({}/\2)'.format(os.getcwd()), line[:-1].replace("'", "\\'"))
    line = re.sub(r'<img src="(.*?)".*?>', r'![]({}/\1)'.format(os.getcwd()), line)
    return line


def main():
    parser = argparse.ArgumentParser(description='markdown 转 html')
    parser.add_argument('doc', help='文档')
    parser.add_argument('style', help='风格', default='united', nargs='?',
                        choices='simplex/lumen/paper/flatly/darkly/yeti/readable/superhero/spacelab/cosmo/cerulean/cyborg/united'.split('/'))
    args = parser.parse_args()
    print(html.format(markdown='+ \n'.join(["'{}\\n'".format(format_line(line))
                                            for line in open(args.doc).readlines()]),
                      title=args.doc, style=args.style))


if __name__ == '__main__':
    main()
