#!/usr/bin/env bash

gitlab="
git@github.com:hatlonely/htool.git
git@github.com:hatlonely/htech.git
git@github.com:hatlonely/helloworld.git
git@github.com:hatlonely/leetcode.git
git@github.com:hatlonely/hellowords.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/mtech/mtool.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/mtech/mtech.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/mtech/mgo.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/vta/rta_unique.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/vta/smartclick.git
http://${GITLAB_USER_PASSWORD}gitlab.mobvista.com/mvdsp/kafka2http.git
"

function main() {
    if [[ ! -z $1 ]]; then
        since=$(echo "--since $1")
    fi
    (hcodestat | hreport)
    for line in ${gitlab}; do
        values=$(echo ${line} | awk -F '[:/.]' 'BEGIN{OFS="\t"}{print $(NF-2),$(NF-1),$0}')
        team=$(echo ${values} | awk '{print $1}')
        proj=$(echo ${values} | awk '{print $2}')
        remote=$(echo ${values} | awk '{print $3}')
        if [[ ! -e ${team}/${proj} ]]; then
            (mkdir -p ${team} && cd ${team} && git clone ${remote})
        fi
        (mkdir -p ${team} && cd ${team}/${proj} && git pull -a && htechstat ${since} | hreport)
    done
}

main "$@"
