#!/usr/bin/env python3

import kafka
import sys


def main():
    producer = kafka.KafkaProducer(bootstrap_servers=['localhost:9092'],
                                   security_protocol='SASL_PLAINTEXT',
                                   sasl_mechanism='PLAIN',
                                   sasl_plain_username='dataplatform',
                                   sasl_plain_password='dataplatform')
    for line in sys.stdin:
        fields = line[:-1].split()
        future = producer.send(topic='adn-tracking_v3_click-log-dt-0', key=fields[0].encode('utf-8'), value=line[:-1].encode('utf-8'))
        meta = future.get(timeout=10)
        print('{}\t{}\t{}\t{}'.format(meta.topic, meta.partition, meta.offset, line))

if __name__ == '__main__':
    main()
